---
# Configuration settings for the application
video:
  scale_factor: 0.25
  buffer_size: 1
  frame_rate: 30
  image_width: 1920
  image_height: 1080
  fourcc: "MJPG"

threshold:
  detection_threshold: 100

server:
  host: "0.0.0.0"
  port: 8080

pushover:
  USER_KEY: ""
  API_TOKEN: ""
  MESSAGE: "Baby's face is covered, or baby has rolled over."
